/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.ThongKeDuNoCtr;
import Model.hoGiaDinh;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lenovo
 */
public class ThongKeDuNoFrm extends javax.swing.JFrame {

    /**
     * Creates new form ThongKeDuNoFrm
     */
    ThongKeDuNoCtr ctr;
    ArrayList<hoGiaDinh> list=new ArrayList<>();
    public ThongKeDuNoFrm() {
        try {
            initComponents();
            ctr=new ThongKeDuNoCtr();
            PopularTable();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ThongKeDuNoFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CustomerNotEnoughPopupMenu = new javax.swing.JPopupMenu();
        SelectMenuItem = new javax.swing.JMenuItem();
        TitleLabel = new javax.swing.JLabel();
        CustomerNotEnoughTableScrollPane = new javax.swing.JScrollPane();
        CustomerNotEnoughTable = new javax.swing.JTable();
        QuayLaiButton = new javax.swing.JButton();

        SelectMenuItem.setText("Xem chi tiết");
        CustomerNotEnoughPopupMenu.add(SelectMenuItem);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TitleLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        TitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleLabel.setText("Thống kê khách hàng nợ nhiều ");
        TitleLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        CustomerNotEnoughTable.setAutoCreateRowSorter(true);
        CustomerNotEnoughTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khách hàng", "Tên khách hàng", "Số điẹn thoại", "Địa chỉ", "Số hóa đơn thanh toán", "Tổng số tiền còn nợ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        CustomerNotEnoughTable.setComponentPopupMenu(CustomerNotEnoughPopupMenu);
        CustomerNotEnoughTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        CustomerNotEnoughTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomerNotEnoughTableMouseClicked(evt);
            }
        });
        CustomerNotEnoughTableScrollPane.setViewportView(CustomerNotEnoughTable);

        QuayLaiButton.setText("Quay lại");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CustomerNotEnoughTableScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1029, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(QuayLaiButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CustomerNotEnoughTableScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(QuayLaiButton)
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CustomerNotEnoughTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomerNotEnoughTableMouseClicked
        DefaultTableModel model = (DefaultTableModel)CustomerNotEnoughTable.getModel();
        int selectRowIndex=CustomerNotEnoughTable.getSelectedRow();
        String id=model.getValueAt(selectRowIndex, 0).toString();
        hoGiaDinh ho=null;
        for (Iterator<hoGiaDinh> it = list.iterator(); it.hasNext();) {
            hoGiaDinh s = it.next();
            if(s.getMaHo().contentEquals(id)){
                ho=s;
                break;
            }
        }
        ThongKeChiTietFrm a=new ThongKeChiTietFrm(ho);
        a.setVisible(true);
    }//GEN-LAST:event_CustomerNotEnoughTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKeDuNoFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKeDuNoFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKeDuNoFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKeDuNoFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ThongKeDuNoFrm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu CustomerNotEnoughPopupMenu;
    private javax.swing.JTable CustomerNotEnoughTable;
    private javax.swing.JScrollPane CustomerNotEnoughTableScrollPane;
    private javax.swing.JButton QuayLaiButton;
    private javax.swing.JMenuItem SelectMenuItem;
    private javax.swing.JLabel TitleLabel;
    // End of variables declaration//GEN-END:variables

    private void PopularTable() {
        try {
            DefaultTableModel model=(DefaultTableModel) CustomerNotEnoughTable.getModel();
            list=ctr.GetHoGiaDinh();
            list.forEach((hoGiaDinh s) -> {
                model.addRow(new Object[]{s.getMaHo(),s.getTenHo(),s.getSdt(),s.getDiaChi(),s.getTongSoHoaDonThanhToan(),s.getSoTienConNo()});
            });
            
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ThongKeDuNoFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
