/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.ThongKeChiTietCtr;
import Model.HoaDon;
import Model.hoGiaDinh;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lenovo
 */
public class ThongKeChiTietFrm extends javax.swing.JFrame {

    /**
     * Creates new form ThongKeChiTietFrm
     */
    ThongKeChiTietCtr ctr;

    public ThongKeChiTietFrm(hoGiaDinh ho) {
        try {
            initComponents();
            ctr = new ThongKeChiTietCtr(ho);
            PopularTable();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ThongKeChiTietFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleLabel = new javax.swing.JLabel();
        CustomerNameLabel = new javax.swing.JLabel();
        CustomerNotDoneLabel = new javax.swing.JLabel();
        CustomerNotEnoughLabel = new javax.swing.JLabel();
        CustomerIdLabel = new javax.swing.JLabel();
        CustomerTelephoneLabel = new javax.swing.JLabel();
        CustomerAddressLabel = new javax.swing.JLabel();
        CustomerNameTextField = new javax.swing.JTextField();
        CustomerIdTextField = new javax.swing.JTextField();
        CustomerTelephoneTextField = new javax.swing.JTextField();
        CustomerAddressTextField = new javax.swing.JTextField();
        CustomerNotDoneTextField = new javax.swing.JTextField();
        CustomerNotEnoughTextField = new javax.swing.JTextField();
        StatBillTableScrollPane = new javax.swing.JScrollPane();
        StatBillTable = new javax.swing.JTable();
        QuayLaiButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TitleLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        TitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TitleLabel.setText("Chi tiết thông tin khách hàng nợ");

        CustomerNameLabel.setText("Tên khách hàng");

        CustomerNotDoneLabel.setText("Tổng số hóa đơn chưa thanh toán");

        CustomerNotEnoughLabel.setText("Tổng số tiền còn nợ");

        CustomerIdLabel.setText("Mã khách hàng");

        CustomerTelephoneLabel.setText("SĐT");

        CustomerAddressLabel.setText("Địa chỉ");

        CustomerNameTextField.setEditable(false);
        CustomerNameTextField.setBorder(null);

        CustomerIdTextField.setEditable(false);
        CustomerIdTextField.setBorder(null);

        CustomerTelephoneTextField.setEditable(false);
        CustomerTelephoneTextField.setBorder(null);

        CustomerAddressTextField.setEditable(false);
        CustomerAddressTextField.setBorder(null);
        CustomerAddressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerAddressTextFieldActionPerformed(evt);
            }
        });

        CustomerNotDoneTextField.setEditable(false);
        CustomerNotDoneTextField.setBorder(null);
        CustomerNotDoneTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerNotDoneTextFieldActionPerformed(evt);
            }
        });

        CustomerNotEnoughTextField.setEditable(false);
        CustomerNotEnoughTextField.setBorder(null);
        CustomerNotEnoughTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerNotEnoughTextFieldActionPerformed(evt);
            }
        });

        StatBillTable.setAutoCreateRowSorter(true);
        StatBillTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Hộ dùng điện", "Thời gian chốt số", "Tổng số điện", "Thành tiền", "Thuế VAT", "Tổng tiền"
            }
        ));
        StatBillTableScrollPane.setViewportView(StatBillTable);

        QuayLaiButton.setText("Quay lại");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(StatBillTableScrollPane, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TitleLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CustomerNameLabel)
                                .addGap(18, 18, 18)
                                .addComponent(CustomerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(CustomerAddressLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CustomerIdLabel)
                                            .addComponent(CustomerTelephoneLabel))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(CustomerTelephoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CustomerIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(CustomerAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CustomerNotDoneLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(CustomerNotDoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(CustomerNotEnoughLabel)
                                .addGap(18, 18, 18)
                                .addComponent(CustomerNotEnoughTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 187, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(QuayLaiButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerNameLabel)
                    .addComponent(CustomerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerIdLabel)
                    .addComponent(CustomerIdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerTelephoneLabel)
                    .addComponent(CustomerTelephoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerAddressLabel)
                    .addComponent(CustomerAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerNotDoneLabel)
                    .addComponent(CustomerNotEnoughLabel)
                    .addComponent(CustomerNotDoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CustomerNotEnoughTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(StatBillTableScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(QuayLaiButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CustomerAddressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerAddressTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerAddressTextFieldActionPerformed

    private void CustomerNotDoneTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerNotDoneTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerNotDoneTextFieldActionPerformed

    private void CustomerNotEnoughTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerNotEnoughTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerNotEnoughTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CustomerAddressLabel;
    private javax.swing.JTextField CustomerAddressTextField;
    private javax.swing.JLabel CustomerIdLabel;
    private javax.swing.JTextField CustomerIdTextField;
    private javax.swing.JLabel CustomerNameLabel;
    private javax.swing.JTextField CustomerNameTextField;
    private javax.swing.JLabel CustomerNotDoneLabel;
    private javax.swing.JTextField CustomerNotDoneTextField;
    private javax.swing.JLabel CustomerNotEnoughLabel;
    private javax.swing.JTextField CustomerNotEnoughTextField;
    private javax.swing.JLabel CustomerTelephoneLabel;
    private javax.swing.JTextField CustomerTelephoneTextField;
    private javax.swing.JButton QuayLaiButton;
    private javax.swing.JTable StatBillTable;
    private javax.swing.JScrollPane StatBillTableScrollPane;
    private javax.swing.JLabel TitleLabel;
    // End of variables declaration//GEN-END:variables

    private void PopularTable() {
        DefaultTableModel model=(DefaultTableModel) StatBillTable.getModel();
        hoGiaDinh ho = ctr.getHo();
        CustomerIdTextField.setText(ho.getMaHo());
        CustomerNameTextField.setText(ho.getTenHo());
        CustomerAddressTextField.setText(ho.getDiaChi());
        CustomerNotDoneTextField.setText(String.valueOf(ho.getTongSoHoaDonThanhToan()));
        CustomerNotEnoughTextField.setText(String.valueOf(ho.getSoTienConNo()));
        CustomerTelephoneTextField.setText(ho.getSdt());
        try {

            ArrayList<HoaDon> list = ctr.GetHoaDon();
            list.forEach((s) -> {
                model.addRow(new Object[]{s.getMaHoaDon(),ho.getTenHo(),s.getNgayTao(),s.getChiSoDien(),s.getThanhTien(),s.getThueVAT(),s.getTongTien()});
            });
            
        } catch (SQLException ex) {
            Logger.getLogger(ThongKeChiTietFrm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
